fixed command deserialization bug
CoralCoralCoralCoral/simulation-engine pull request #33
Opened 2024-12-05 01:46 UTC by umran

addresses #32

2024-12-06 22:04 UTC, sah339 requested changes

2024-12-06 22:04 UTC, sah339 commented on .github/workflows/runUnitTests.yml
> +                  go-version: "1.21" # Specify the Go version you want to use
Should this be 1.23?

2024-12-06 22:04 UTC, sah339 commented on model/command_test.go
> +	}
Not a necessary change but could consider using [stretchr/testify](https://pkg.go.dev/github.com/stretchr/testify) for the test assertions

2024-12-06 22:04 UTC, sah339 commented on model/simulation.go
> +	logger_ := logger.NewLogger()
Any reason this name is prepended with an underscore?

2024-12-07 14:04 UTC, umran commented on model/simulation.go
> +	logger_ := logger.NewLogger()
yeah, it's to avoid shadowing `logger` the package. couldn't think of a better name than logger_ at the time

2024-12-07 14:04 UTC, umran commented on .github/workflows/runUnitTests.yml
> +                  go-version: "1.21" # Specify the Go version you want to use
ah yes, should be 1.23

2024-12-07 14:06 UTC, umran commented on model/command_test.go
> +	}
good catch. i was actually meaning to use testing's built in assertions. is there a reason we would want to use an external dependency vs testing?

2024-12-07 14:18 UTC, umran commented on model/command_test.go
> +	}
just realized testing does not have built-in assertions

2024-12-07 14:29 UTC, umran commented on model/command_test.go
> +	}
just changed it to use testify

2024-12-07 17:01 UTC, sah339 approved these changes

2024-12-07 17:11 UTC, merged